services:
  adminarr:
    container_name: adminarr
    build: .
    image: ghcr.io/plexd281knilb/adminarr:latest
    restart: unless-stopped
    user: root 
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NODE_ENV=production
    volumes:
      - ./prisma:/app/prisma
      - ${ARRAY_MOUNT_PATH:-/mnt/user}:${ARRAY_MOUNT_PATH:-/mnt/user}
      - ${REMOTES_MOUNT_PATH:-/mnt/remotes}:${REMOTES_MOUNT_PATH:-/mnt/remotes}